### ISSUE TITLE
Standardize version naming

### ISSUE THREAD

**Issue by glneo** [TexasInstruments/debian-repos#6]
The package versions used in debian/changelog need a little work. The version should match the latest tag in the upstream project, for example [0] is labeled 0.8-1, but the upstream is based two commits ahead of the tag `R8.8`. I'd also suggest since we are not basing this on an upstream Debian package yet, we should not use any debian_revision, or set it to 0. We should also add our own rev tag to make these easy to track. Lastly since this is not actually a release, but instead 2 patches ahead of one, we should include the git SHA (or just have the number of patches ahead in the .patch, but not sure how I feel about this actually.. SHA is probably better but it should be prepended with a date to keep the version increasing).

So in this case the version would be (8.8.2-0ti1).

[0] https://github.com/TexasInstruments/debian-repos/blob/fbc6f76738559225bc18760dd65f8d4cb3c3347e/wl18xx-ti-utils/suite/bookworm/debian/changelog#L1C23-L1C23

**Comment by sskartheekadivi** [comment]
Yes @glneo. Package versioning needs to be updated. I'm currently rebuilding all the packages as part of migration to the [restructured TI PPA](https://github.com/TexasInstruments/ti-debpkgs). So will update the versioning as well along the way.

**Comment by sskartheekadivi** [comment]
All the packages that were rebuilt and uploaded to the restructured PPA are properly versioned. Please reopen this or create a new issue if you find some package which is not following proper version conventions.
